version: "3"
services:
  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root # change this to your root password
      - MYSQL_DATABASE=smsd
      - MYSQL_USER=smsd
      - MYSQL_PASSWORD=smsd # change this to your user password
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
  nodejs:
    build:
      context: .
      dockerfile: ./Dockerfile # change this to your dockerfile path
    depends_on:
      - mariadb
    ports:
      - 3000:3000 # change this to your desired port
    volumes:
      - node_modules:/usr/src/app/node_modules
    restart: always

volumes:
  node_modules:
    name: "zlatni-cesalj-sms-gateway"
