version: "3"
services:
  mariadb:
    image: mariadb
    container_name: MySQL
    environment:
      - MYSQL_ROOT_PASSWORD=root # change this to your root password
      - MYSQL_DATABASE=smsd
      - MYSQL_USER=smsd
      - MYSQL_PASSWORD=smsd # change this to your user password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql-scripts:/docker-entrypoint-initdb.d
    restart: always

  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: PhpMyAdmin
    restart: always
    ports:
      - 5013:80
    environment:
      - PMA_ARBITRARY=1

  nodejs:
    build:
      context: .
      dockerfile: ./Dockerfile # change this to your dockerfile path
    depends_on:
      - mariadb
    ports:
      - 3000:3000 # change this to your desired port
    volumes:
      - node_modules:/usr/src/app/node_modules
    restart: always

volumes:
  node_modules:
  mysql-data:
